### ISSUE TITLE
No code?

### ISSUE THREAD

**Issue by HillJD** [HillJD/Road2Harvest#1]
There is no code in this repository.  Please correct this deficiency.

**Comment by HillJD** [comment]
![4apr12](https://cloud.githubusercontent.com/assets/23171999/19939044/ad74e012-a0fd-11e6-8f9e-315a85a68a1a.jpg)
We can communicate needs in the issues tool (even include attachments)

**Comment by HillJD** [comment]
re-opening this issue as that Hillen guy still hasn't posted any code

**Comment by WaltMR** [comment]
This definitely looks like a good way to discuss coding and debugging. This way we can keep issues, topics, etc in separate threads to keep them from getting jumbled in emails.
