### ISSUE TITLE
Lowering the bar

### ISSUE THREAD

**Issue by HillJD** [HillJD/Road2Harvest#18]
I apologize if I caused this error, but the gold bar under the header is raised up on all the pages.
![image](https://user-images.githubusercontent.com/23171999/32703022-edc5c2a2-c7bd-11e7-8498-b862593f7f4d.png)

**Comment by dearthm** [comment]
I'll take care of it.
Mike D

**Comment by dearthm** [comment]
Resolved. Mike D

**Comment by HillJD** [comment]
Thanks Mike.  It's better, but still  little 'funky'.  Could you please look again?   ....and I apologize profusely for breaking this.
![image](https://user-images.githubusercontent.com/23171999/32814749-503a5e86-c97e-11e7-9155-77016587344a.png)
