### ISSUE TITLE
Listen Verbiage

### ISSUE THREAD

**Issue by HillJD** [HillJD/Road2Harvest#20]
Tim and I were talking and I understand that Mike Dearth was also in agreement that the wording on the listen page could be improved a little.

Each button should begin with a verb and include the best object description possible.  Something like:
Stream Sermons 24/7 (We Are Live)
Search Archives
Find Us on TuneIn

It just seemed confusing that the first two buttons start with "listen".  Let's see if we can make this a little better.

![image](https://user-images.githubusercontent.com/23171999/32815033-da9030be-c97f-11e7-898d-835c890493c9.png)

**Comment by Parcliff** [comment]
I really like the view when accessing “sermon archive.”  This may have already been addressed, but on Iphone 6s the “play arrow” is off to the right out of view, and one must horizontally scroll right to see it.  I am afraid that most won’t be able to find the arrow.

 

Thanks,

C. Hurst
