### ISSUE TITLE
Enlarged Header 

### ISSUE THREAD

**Issue by el0552t** [HillJD/Road2Harvest#28]
Header on PC is enlarged. Verified on both Chrome and IE

![capture](https://user-images.githubusercontent.com/23223567/33213172-85123b56-d0f4-11e7-88c6-29ed83f0a8f3.JPG)

**Comment by HillJD** [comment]
I believe that this is resolved.  Please confirm and close if possible.

**Comment by HillJD** [comment]
I tried this on several platforms and it performs well.  Closing issue.
