### ISSUE TITLE
Typo - Ministries / Groups

### ISSUE THREAD

**Issue by el0552t** [HillJD/Road2Harvest#30]
Youth Nights - Youth (10yo and up) are invited....

Also, Isn't it 12 years and up?

**Comment by Bmckelvey** [comment]
Good catch. Yes it is. 


Bryan

**Comment by HillJD** [comment]
Could I please get the exact text to insert for "Youth Nights" please?

**Comment by Bmckelvey** [comment]
Just need to replace the age 10 with 12.
