### ISSUE TITLE
Tunein Icon Outdated

### ISSUE THREAD

**Issue by el0552t** [HillJD/Road2Harvest#32]
Tunein icon outdated on Listen page

**Comment by HillJD** [comment]
Tyler - you're going to need to investigate the ownership of our TuneIn account.  There ought to be some info in Google.  You may need to call TuneIn support.  Go and get it done!  Have fun!

**Comment by WaltMR** [comment]
This issue is the tunein logo on our site. This ones mine. I will create a second issue for our logo on tunein

**Comment by HillJD** [comment]
I see a commit, but the change was not published?

**Comment by WaltMR** [comment]
Correct. I was having trouble publishing for some reason.
